<?xml version="1.0"?>
<test:suite 
	xmlns:j="jelly:core" 
	xmlns:test="jelly:junit"
	xmlns:v="jelly:validate">

<!-- test RelaxNG --> 

<test:case name="validateRelaxNG">

<v:verifier uri="address.rng" var="addressSchema"/>

<v:assertValid verifier="${addressSchema}">
  <addressBook>
    <card>
      <name>John Smith</name>
      <email>js@example.com</email>
    </card>
    <card>
      <name>Fred Bloggs</name>
      <email>fb@example.net</email>
    </card>
  </addressBook>
</v:assertValid>
  
</test:case>


<test:case name="invalidateRelaxNG">

<v:verifier uri="address.rng" var="addressSchema"/>

<j:catch var="exception">
<v:assertValid var="flag" verifier="${addressSchema}">
  <addressBook>
    <card>
      <email>js@example.com</email>
    </card>
    <card>
      <name>Fred Bloggs</name>
    </card>
    <card>
      <wrongname>Fred Bloggs</wrongname>
    </card>
    <card>
    </card>
  </addressBook>
</v:assertValid>
</j:catch>

<test:assert test="${!flag}">The document should not be valid</test:assert>
<test:assert test="${exception != null}">An exception should have been thrown</test:assert>
The exception was ${exception.message}
  
</test:case>


<!-- test DTDs --> 
<test:case name="validateDTD">

<v:verifier uri="address.dtd" var="addressSchema"/>

<v:assertValid verifier="${addressSchema}">
  <addressBook>
    <card>
      <name>John Smith</name>
      <email>js@example.com</email>
    </card>
    <card>
      <name>Fred Bloggs</name>
      <email>fb@example.net</email>
    </card>
  </addressBook>
</v:assertValid>
  
</test:case>


<test:case name="invalidateDTD">

<v:verifier uri="address.dtd" var="addressSchema"/>

<j:catch var="exception">
<v:assertValid var="flag" verifier="${addressSchema}">
  <addressBook>
    <card>
      <email>js@example.com</email>
    </card>
    <card>
      <name>Fred Bloggs</name>
    </card>
    <card>
      <wrongname>Fred Bloggs</wrongname>
    </card>
    <card>
    </card>
  </addressBook>
</v:assertValid>
</j:catch>

<test:assert test="${!flag}">The document should not be valid</test:assert>
<test:assert test="${exception != null}">An exception should have been thrown</test:assert>
The exception was ${exception.message}
  
</test:case>
   
</test:suite>
