<?xml version="1.0"?>
<test:suite xmlns:j="jelly:core" xmlns:test="jelly:junit" xmlns:x="jelly:xml">

  <test:case name="assertTests">
  
    <test:assert test="${2 == 2}">This should never fail</test:assert>
    
    <j:catch var="ex">
	  <test:assert test="${2 != 2}">This should always fail</test:assert>
	</j:catch>    	
	
	<test:assert test="${ex != null}">We should have created an exception</test:assert>
	
	The exception was: ${ex.message}
  </test:case>


  <test:case name="assertXPathTests">
  
    <x:parse var="doc">
      <foo>
      	<bar>cheese</bar>
      </foo>
    </x:parse>  
     
  
    <test:assert xpath="$doc/foo/bar">This should never fail</test:assert>
    <test:assert xpath="$doc/foo/bar = 'cheese'">This should never fail</test:assert>
    
    <j:catch var="ex">
		  <test:assert xpath="$doc/foo/xyz">This should always fail</test:assert>
		</j:catch>    	
		
		<test:assert test="${ex != null}">We should have created an exception</test:assert>
		
		The exception was: ${ex.message}
  </test:case>

	<!-- test the use of namespaces with XPath -->
  <test:case name="assertXPathWithNamespaceTests" xmlns:a="fooURI" xmlns:z="doesNotMatch">
  
    <x:parse var="doc">
      <foo xmlns="fooURI">
      	<bar>cheese</bar>
      </foo>
    </x:parse>  
     
    <test:assert xpath="$doc/a:foo/a:bar">This should never fail</test:assert>
    <test:assert xpath="$doc/b:foo/b:bar" xmlns:b="fooURI">This should never fail</test:assert>
    
    <j:catch var="ex">
		  <test:assert xpath="$doc/z:foo/z:bar">This should always fail</test:assert>
		</j:catch>    	
		
		<test:assert test="${ex != null}">We should have created an exception</test:assert>
		
    <j:catch var="ex">
		  <test:assert xpath="$doc/foo/bar">This should always fail, since foo is not in the empty namespace</test:assert>
		</j:catch>    	
		
		<test:assert test="${ex != null}">We should have created an exception</test:assert>
  </test:case>


  <test:case name="failTests">
  
    <j:catch var="ex">
	  <test:fail>This should always fail</test:fail>
	</j:catch>    	
	
	<test:assert test="${ex != null}">We should have created an exception</test:assert>
	
	The exception was: ${ex.message}
	
    <j:catch var="ex">
	  <test:fail message="This should always fail"/>
	</j:catch>    	
	
	<test:assert test="${ex != null}">We should have created an exception</test:assert>
	
	The exception was: ${ex.message}
  </test:case>

	
  <test:case name="assertEqualTests">
  
    <j:set var="foo" value="abc"/>
    
    <test:assertEquals actual="${foo}" expected="abc">This should never fail</test:assertEquals>
    
    <j:catch var="ex">
      <test:assertEquals actual="${foo}" expected="def">This should always fail</test:assertEquals>
	</j:catch>    	
	
	<test:assert test="${ex != null}">We should have created an exception</test:assert>
	
	The exception was: ${ex.message}
  </test:case>

<!--
	
	#### uncomment when assertEquals supports type conversions
	
  <test:case name="assertEqualsConversion">
  
		<test:assertEquals expected="${4}" actual="${2+2}"/>

  </test:case>
-->

</test:suite>
